### ISSUE TITLE
GCC 10+ issues

### ISSUE THREAD

**Issue by idsardi** [lucadn/xkl#1]
I've only tried compiling this on Debian 12, which has gcc 12. Since gcc 10, the compiler defaults to -fno-common, https://gcc.gnu.org/gcc-10/porting_to.html . This causes a bunch of errors for multiple definitions. The short-term fix is to add -fcommon to the CFLAGS list in the Makefile.vars file.

**Comment by lucadn** [comment]
Hi William,

thanks for the feedback! I updated the file. The plan is eventually to move away to motif and to gtk, but in the mean time we try to keep the software usable in its current form...
